import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Plus, HelpCircle, ArrowRight } from "lucide-react";
import { FadeIn, SectionHeading } from "./ui";
import type { FAQSectionData } from "../store/siteStore";

export function FAQ({ dynamicData }: { dynamicData?: FAQSectionData }) {
  const [open, setOpen] = useState<number | null>(0);
  const [showAllInline, setShowAllInline] = useState(false);

  const d: FAQSectionData = dynamicData || {
    eyebrow: "FAQ",
    title: "Everything you need",
    titleAccent: "to know.",
    subtitle:
      "Still have questions? Our 24×7 support team replies in under 2 minutes on WhatsApp.",
    supportTitle: "Talk to a human in under 2 minutes.",
    supportSubtitle:
      "Our India-based support team is online 24×7 — in Hindi, English, and 8 regional languages.",
    whatsappCta: "Chat on WhatsApp",
    emailCta: "support@teenpattistars.in",
    items: [
      {
        id: "q1",
        q: "Is Teen Patti Stars legal in India?",
        a: "Yes. Teen Patti is classified as a game of skill by the Supreme Court of India and is legal in most states. We operate under a Curacao gaming license and comply with all IT Act and FEMA regulations. Note: a few states (Telangana, Andhra Pradesh, Tamil Nadu, Karnataka, Odisha, Assam) restrict real-money gaming — we geo-block users from these states.",
      },
      {
        id: "q2",
        q: "How fast are withdrawals really?",
        a: "Our median UPI payout is 28 seconds. 99.94% of all withdrawals in 2025 were processed in under 5 minutes. We support UPI, IMPS, Paytm, GPay, and PhonePe. No paperwork, no minimum limit beyond ₹100, and no cap on daily withdrawals for verified users.",
      },
      {
        id: "q3",
        q: "Is the game fair? How do I know there are no bots?",
        a: "Every shuffle is generated by a Quantum RNG seed audited weekly by iTech Labs (Certificate #TPS-2025-041). We run a real-time collusion detection engine and employ former cybersecurity analysts from Flipkart and Razorpay to monitor gameplay. Third-party audits are published on our transparency page every quarter.",
      },
      {
        id: "q4",
        q: "What is the ₹500 welcome bonus?",
        a: "New verified players receive ₹500 in bonus credits after completing KYC (Aadhaar + PAN). Bonus credits can be used on any table with a 5× rollover before withdrawal. There is no deposit required to claim the welcome bonus — though a ₹100 first deposit unlocks an additional ₹200 bonus.",
      },
      {
        id: "q5",
        q: "Can I play with friends privately?",
        a: "Yes. Create a private table in under 10 seconds, set the boot, invite friends via a shareable link or WhatsApp, and play with voice chat built in. Private tables are rake-free for all users. Works on both Android and iOS.",
      },
      {
        id: "q6",
        q: "What happens if I suspect someone is cheating?",
        a: "Report any suspicious player in-app. Our trust & safety team investigates within 2 hours. If cheating is confirmed, the offending account is banned and forfeited chips are redistributed to affected players. We've refunded over ₹4.2 Cr to players via this program.",
      },
      {
        id: "q7",
        q: "Do you support responsible gaming?",
        a: "Absolutely. Every user can set daily deposit limits, weekly loss limits, session timers, and self-exclusion periods. Our AI detects problem-gambling patterns and proactively reaches out. We partner with HOPE Foundation and donate 0.5% of rake to gaming addiction support.",
      },
      {
        id: "q8",
        q: "Which devices are supported?",
        a: "Teen Patti Stars runs natively on Android 7+ and iOS 14+. The app is under 45 MB, works on 4G, and supports low-end devices. We also offer a web version at play.stars for desktop players.",
      },
    ],
  };

  const displayedItems = showAllInline ? d.items : d.items.slice(0, 3);

  return (
    <section id="faq" className="relative overflow-hidden py-24 md:py-32">
      <div className="mx-auto w-full max-w-4xl px-6">
        <SectionHeading
          eyebrow={d.eyebrow}
          title={d.title}
          titleAccent={d.titleAccent}
          subtitle={d.subtitle}
        />

        <div className="space-y-3">
          {displayedItems.map((f, i) => (
            <FadeIn key={f.id || f.q} delay={i * 0.04}>
              <FAQItem
                question={f.q}
                answer={f.a}
                open={open === i}
                onToggle={() => setOpen(open === i ? null : i)}
              />
            </FadeIn>
          ))}
        </div>

        {/* View All on FAQ Page banner */}
        {d.items && d.items.length > 0 && (
          <FadeIn delay={0.08}>
            <div className="mt-8 flex flex-col sm:flex-row items-center justify-between gap-4 rounded-2xl border border-white/10 bg-white/[0.02] p-5 backdrop-blur-xl">
              <div className="flex items-center gap-3.5">
                <div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                  <HelpCircle className="h-5 w-5" />
                </div>
                <div>
                  <div className="text-sm font-bold text-white">
                    Showing {Math.min(displayedItems.length, d.items.length)} of {d.items.length} Essential Questions
                  </div>
                  <p className="text-xs text-white/50">
                    Explore full answers on legal precedents, payouts, game variants, and VIP rewards.
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-2.5 w-full sm:w-auto justify-end">
                {d.items.length > 3 && (
                  <button
                    onClick={() => setShowAllInline(!showAllInline)}
                    className="rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-xs font-semibold text-white/70 hover:bg-white/10 hover:text-white transition-all whitespace-nowrap"
                  >
                    {showAllInline ? "Show 3 Only" : `Expand Here (${d.items.length - 3})`}
                  </button>
                )}

                <a
                  href="/faq"
                  className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-emerald-500 to-emerald-600 px-5 py-2.5 text-xs font-bold text-white shadow-lg shadow-emerald-500/20 hover:brightness-110 active:scale-95 transition-all whitespace-nowrap"
                >
                  <span>View Full FAQ Page</span>
                  <ArrowRight className="h-3.5 w-3.5" />
                </a>
              </div>
            </div>
          </FadeIn>
        )}

        <FadeIn delay={0.1}>
          <div className="mt-12 rounded-2xl border border-white/10 bg-gradient-to-br from-emerald-500/5 via-white/[0.02] to-transparent p-8 text-center">
            <div className="mb-2 text-sm uppercase tracking-widest text-emerald-300">
              Still stuck?
            </div>
            <h3 className="text-2xl font-semibold tracking-tight text-white md:text-3xl">
              {d.supportTitle}
            </h3>
            <p className="mx-auto mt-3 max-w-md text-white/60">
              {d.supportSubtitle}
            </p>
            <div className="mt-6 flex flex-wrap items-center justify-center gap-3">
              <a
                href="https://wa.me/919876543210"
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center gap-2 rounded-full bg-white px-6 py-3 text-sm font-semibold text-[#05080a] transition-all hover:bg-white/90"
              >
                {d.whatsappCta || "Chat on WhatsApp"}
              </a>
              <a
                href={`mailto:${d.emailCta || "support@teenpattistars.in"}`}
                className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-6 py-3 text-sm font-medium text-white transition-all hover:bg-white/10"
              >
                {d.emailCta || "support@teenpattistars.in"}
              </a>
            </div>
          </div>
        </FadeIn>
      </div>
    </section>
  );
}

function FAQItem({
  question,
  answer,
  open,
  onToggle,
}: {
  question: string;
  answer: string;
  open: boolean;
  onToggle: () => void;
}) {
  return (
    <div
      className={`overflow-hidden rounded-2xl border transition-all duration-500 ${
        open
          ? "border-emerald-400/30 bg-gradient-to-br from-emerald-500/[0.06] to-transparent"
          : "border-white/10 bg-white/[0.02] hover:border-white/20"
      }`}
    >
      <button
        onClick={onToggle}
        className="flex w-full items-center justify-between gap-4 px-6 py-5 text-left"
      >
        <span className="text-[15px] font-medium text-white md:text-base">
          {question}
        </span>
        <div
          className={`grid h-7 w-7 shrink-0 place-items-center rounded-full border transition-all duration-300 ${
            open
              ? "rotate-45 border-emerald-400/40 bg-emerald-400/20"
              : "border-white/15 bg-white/5"
          }`}
        >
          <Plus
            className={`h-3.5 w-3.5 ${open ? "text-emerald-300" : "text-white/70"}`}
            strokeWidth={2.5}
          />
        </div>
      </button>

      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.4, ease: [0.2, 0.8, 0.2, 1] }}
          >
            <div className="px-6 pb-6 text-[15px] leading-relaxed text-white/65">
              {answer}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
